---
title: RESTEASY-2505工作笔记（四）
---

### org.jboss.resteasy.spi里面的RuntimeException exceptions

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun05/Class Diagram9.png)

### ExceptionHandlerTest的testApplicationExceptionMapper()

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun05/D90DC96A-FC6C-4AD1-9870-7C6A96B345E8.png)

这个测试分为两部分，第一部分是测试`WebApplicationException`的默认工作机制，第二部分是把测试定义的`SprocketDBException`这个自定义的Exception去用自定义的`ApplicationExceptionMapper`去处理。下面是测试的时序图：

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun05/org.jboss.resteasy.test.mapper.ExceptionHandlerTest.testApplicationExceptionMapper().png)

### testUnhandledException()

这个测试是测试未封装的`SprocketDBException`，而这个exception是扩展`RuntimeException`，下面是图：

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun05/Class Diagram10.png)

测试的逻辑图：

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun05/org.jboss.resteasy.test.mapper.ExceptionHandlerTest.testUnhandledException().png)

测试的代码：

![](https://raw.githubusercontent.com/liweinan/blogpic2020_ii/master/jun05/4AAF8B7B-217E-44C3-AC30-56FA799171BB.png)

可以看到最后exception mapper抛出的实际上是`UnhandledException`。


