---
title: RESTEASY-2505工作笔记（七）
---

Reproducer：[update · liweinan/RESTEasy2505Reproducer@a90d88f · GitHub](https://github.com/liweinan/RESTEasy2505Reproducer/commit/a90d88f7521cea3d488b97153ace26e9c150f935)

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/541B95D6-765D-4607-B0FC-D5F598CD8F77.png)

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/6A082955-E35D-4F8A-97CC-CAF4BC97F5F6.png)

从协议分析可以看出服务端并没有把`v0id`发回来：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/F6B8E91C-8C48-4118-8A4A-4632C0D7A6EA.png)

可以看到`WebApplicationException`：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/BDFC5E87-EF49-4514-A3AE-7AA359383CBA.png)

看一下抛出的轨迹：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/D3EFBA5B-E7AE-4ED9-8EE7-6724D6275608.png)

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/93B53F08-805E-4E0B-ACC8-0FE886C720D0.png)

分析一下`theResponse`：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/C1DC4343-7263-4E82-ADE5-35754168D1D0.png)

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/D8476B96-B33D-47A8-8DBF-0507CF96AE33.png)

对比一下`cool`方法：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/12EE3B0A-F3C7-4C85-96A3-A24CC486D7AC.png)

上面这个方法不会触发这里：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/4231E51D-A51D-4E4E-B8CD-B386BD7A6E22.png)

直接封装进response了：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/38B25F9A-3AC8-4E07-ACF0-009A51574E1E.png)

以上就是root cause。

做一个新的方法：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/11DF5303-4753-42AF-802F-43674BE25CEF.png)

使用`httpie`请求如下：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/45A12B84-894B-4674-865F-36F2252E8A6C.png)

可以看到服务端抛出了`v0id2`。

使用`foo.v0id2()`方法来呼叫：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/725E21A0-F14E-4159-8810-FA638A03F61A.png)

可以看到服务端仍然抛出`v0id2`：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/1574CF75-204F-4C15-8AC3-6CFE52DC953B.png)

客户端代理class捕获了错误：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/D0122005-6579-48C1-851A-98E3E87CFCC5.png)

但是通过上面协议分析可以看到服务端并没有返回具体的错误信息给服务端。

如果加入一个exception mapper：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/66C9817F-5B49-4BC3-943D-2AE7F55E21F0.png)

那么客户端就可以得到信息：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/2CB7248D-64DE-4E56-BDDE-51CEDDCEE724.png)

wireshark也可以确认这一点：

![](https://raw.githubusercontent.com/liweinan/blogpic2020iii/master/jul02/C4677079-59D5-4529-AD2D-F7438FD9990B.png)

因此确认这个模式应该不是bug。



